### ISSUE TITLE
redpen.cc documentation links to previous versions are broken

### ISSUE THREAD

**Issue by kenhys** [recruit-tech/redpen-doc#15]
http://redpen.cc/docs.html follows 0.6 and 1.2 documents.

But both of them are not found.

**Comment by takahi-i** [comment]
Thank you a lot for the report @kenhys! I will fix the missing links.

**Comment by takahi-i** [comment]
I fixed the missing links.

**Comment by kenhys** [comment]
Thanks!
I've confirmed that missing links are fixed, so close this issue.

**Comment by takahi-i** [comment]
Thank you!
